import './globals.css'
import {Metadata} from "next";

export const metadata: Metadata = {
  title: 'Auction Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
